name: Release
on:
  push:
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14]
        os: ["ubuntu-20.04", "macos-11", "windows-2019"]
    steps:
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64

      - name: Set up Go 1.18.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
        id: go

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Step pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build frontend
        run: make build-frontend

      - name: Build go binary
        run: make release-build

      - name: compress go binary
        if: github.ref_type == 'tag'
        shell: bash
        run: for i in edgeRec_*; do zip "$(echo $i | sed 's/\..*//').zip" $i || 7z a -tzip "$(echo $i | sed 's/\..*//').zip" $i; done

      - name: Upload Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: edgeRec*.zip
          draft: true

