name: Release
on:
  push:
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "debian:10.3"
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: Set up Go 1.18.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
        id: go

      - name: Instasll tools
        shell: bash
        run: "apt update && apt install make curl gcc ca-certificates zip git -y"

      - name: Install gox
        run: go install github.com/mitchellh/gox@master

      - name: Instasll node apt repo
        shell: bash
        run: "curl -sL https://deb.nodesource.com/setup_14.x | bash -"

      - name: Instasll node
        shell: bash
        run: "apt install nodejs -y"

      - name: Step pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build frontend
        run: make build-frontend

      - name: Build go binary
        shell: bash
        run: gox -cgo -osarch='darwin/arm64 darwin/amd64 windows/arm64 windows/amd64 linux/arm64 linux/amd64' -ldflags="
              -X main.Version=$(git describe --tags $(git rev-parse HEAD))
              -X main.Commit=$(git rev-parse HEAD)" ./

      - name: compress go binary
        if: github.ref_type == 'tag'
        shell: bash
        run: for i in edgeRec_*; do zip "$(echo $i | sed 's/\..*//').zip" $i; done

      - name: Upload Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: edgeRec*.zip
          draft: true
